# Generated by Django 4.2.7 on 2023-11-16 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('isFinished', models.BooleanField(default=False, verbose_name='finished')),
                ('mtgFormat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mformat', to='base.mtgformat')),
                ('myDeck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mydeckname', to='base.deck')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('theirname', models.CharField(max_length=100, null=True)),
                ('inLeagueNum', models.IntegerField(null=True)),
                ('game1', models.BooleanField(default=False, help_text='win', verbose_name='Win')),
                ('game2', models.BooleanField(default=False, verbose_name='Win')),
                ('game3', models.BooleanField(default=None, null=True, verbose_name='Win')),
                ('didjawin', models.BooleanField(default=False, verbose_name='Match Win')),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='base.league')),
                ('mtgFormat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtgFormat', to='base.mtgformat')),
                ('myDeck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mydeck', to='base.deck')),
                ('theirArchetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theirarchetype', to='base.archetype', verbose_name='Their Archetype')),
                ('theirDeck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theirdeck', to='base.deck', verbose_name='Their Deck')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
