# Generated by Django 4.2.7 on 2023-11-25 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='myFlavor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myflavorl', to='base.flavor'),
        ),
        migrations.AddField(
            model_name='match',
            name='theirFlavor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theirflavors', to='base.flavor', verbose_name='Thier Flavor'),
        ),
        migrations.AlterField(
            model_name='league',
            name='myDeck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mydeckl', to='base.deck'),
        ),
    ]
