# Generated by Django 4.2.7 on 2023-11-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_league_myflavor_match_theirflavor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game1',
            field=models.BooleanField(default=None, help_text='win', null=True, verbose_name='Win'),
        ),
        migrations.AlterField(
            model_name='match',
            name='game2',
            field=models.BooleanField(default=None, null=True, verbose_name='Win'),
        ),
    ]
