# Generated by Django 4.2.7 on 2023-11-28 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_match_game1_alter_match_game2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='myFlavor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myflavorl', to='base.flavor'),
        ),
        migrations.AlterField(
            model_name='match',
            name='game1',
            field=models.BooleanField(default=None, help_text='win', null=True, verbose_name='Win1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='game2',
            field=models.BooleanField(default=None, null=True, verbose_name='Win2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='game3',
            field=models.BooleanField(default=None, null=True, verbose_name='Win3'),
        ),
    ]
